### ISSUE TITLE
vvtts のコードに対する質問

### ISSUE THREAD

**Issue by sandonemaki** [noir55/voicevox_cli_client#1]
こんにちは。
Rubyを勉強しているものです。
noir55 さんのコードリーディングをさせていただきまして、どうしても質問させていただきたかったのですが、連絡手段がなかったので、issueを作成いたしました。

早速質問ですが、
1. [こちらの行](https://github.com/noir55/voicevox_cli_client/blob/82e9831c12bf68246f77b1d90d1a446ab09951ae/bin/vvtts#L372)で wavs を引数にとっているようですが、 wavs はJSONデータを音声データに変換し、実体化された wav データを wavs としているのでしょうか？ それともクエリ作成でレスポンスされた JSON のことでしょうか？
1.  [chunk についてですが](https://github.com/noir55/voicevox_cli_client/blob/82e9831c12bf68246f77b1d90d1a446ab09951ae/bin/vvtts#L412)、wav データとして保存されたデータから chunk data を読み込んでいるのでしょうか？ それともレスポンスされたJSONから読み込むことができるのでしょうか？
1. chunk について無知であるため、どうやってロジックを組まれたのかを知りたいのですが可能でしょうか？　
  参考記事なども教えていただけると嬉しいです。
1. wav data の結合において、ffmpeg でも同じことができると聞いたのですが、使用しなかった理由は何でしょうか。
1. wav data として保存してから interval silent、fast silent などを追加し、結合する実装を書かれた理由を教えていただけますでしょうか。

お忙しいと思うのですが、とても興味があり、できれば早く知りたいと思っています。
どうぞ、よろしくお願いいたします。

**Comment by sandonemaki** [comment]
こちら解決しましたのでcloseにさせていただきます。
（削除して頂いても大丈夫です。）

**Comment by noir55** [comment]
解決されたようですが回答いたします。

1. wavsは配列で、個々の要素にVOICEVOX ENGINEが返してきたwav形式のデータが格納されています
1. wavデータから読み込んでいます。wavデータはチャンクに音声データの長さなどを持っています。このため、音声データを結合するには個々のwavデータのチャンクを読み取り、結合後のwavデータ用のチャンクを生成する必要があります。
1. 特にどのサイトをということはありませんが、「wav フォーマット」でウェブ検索してwavファイルのフォーマットを調べました。
1. wavフォーマットを調べてみて、無音を挟んだ結合程度なら自分でも実装できるかも、と思ったので挑戦してみました。このほうが処理時間も短くできるというメリットもありますし。
1. コマンドオプションや設定ファイルで無音時間を設定して結合できるようにしたかったので、私なりに考えた結果こうするのがよさそうという程度の理由です。

私もコーディングはウェブ検索に頼りっぱなしですので、とりあえず動くレベルのコードだと思います。なので、わざわざ読んでいただいたことにありがたいような申し訳ないような気持ちになりましたが、参考になったのでしたら幸いです。

**Comment by sandonemaki** [comment]
ご回答ありがとうございます。
とても嬉しいです。
waxデータを調べていくうちに、「wavフォーマット」という単語がどうやらあるらしいということにたどり着いてからは、noir55 さんがおっしゃっている内容に関する理解が出来き、問題解決に至りました。

いただいたお返事のついでで申し訳ないのですが、もう一つお聞きしたいことがあります。
voicevox のエンジンを複数立ち上げれるようにした理由は、片方のエンジンが起動しなかった時のためでしょうか？

00行まではエンジン１というように振り分ける事ができたら、音声合成の高速化ができるのではと色々考えては楽しくなりました。

**Comment by noir55** [comment]
複数のエンジンを利用できるようにしたのは、sandonemakiさんが最後に書かれている、エンジンを複数使って音声変換を高速化したいという意図です。Dockerを使えば簡単にVOICEVOX ENGINEを立ち上げることができるので、複数のPC上でエンジンを実行すればそれらを使って並列で音声変換できるな…と思ったのがきっかけで実装してみました。私にはDockerを使える複数PCの環境がないので、自分で恩恵にあずかることができていないのが残念ですが。。。

**Comment by sandonemaki** [comment]
ありがとうございます。私はまだDockerが使えないのですが、環境が揃ったら試してみようかと思います！

**Comment by sandonemaki** [comment]
方法としては、以下のようなイメージで考えているのですが合っていますでしょうか？

a -１：１つ目のテキストをエンジン a にクエリ作成のリクエスト -> レスポンス
a -２：パラメーターの設定をしてエンジン a にリクエスト -> レスポンス
b -１：２つ目のテキストをエンジン b にクエリ作成のリクエスト -> レスポンス
b -２：パラメーターの設定をしてエンジン b にリクエスト -> レスポンス
エンジン a のレスポンス、エンジン b のレスポンスを配列に入れる。
配列 [0] を音声ファイルに変換、配列 [1] を音声ファイルに変換、それらを結合した音声ファイルを作成。

**Comment by noir55** [comment]
音声変換処理をマルチスレッドで実行することで並列化しています。メインの処理とは別の子スレッドとしてテキスト音声変換処理を実行し、変換後の音声データをメインの処理に返しています。なので、「a-1→a-2」「b-1→b-2」をそれぞれ子スレッドとして並列実行しています。

具体的には、vvttsバージョン1.2.7の場合
1. エンジンの数と同じ個数の音声変換スレッドを生成(1309～1353行目)
1. スレッドの状態を監視し、いずれかのスレッドが終了したら音声データを回収して配列に格納し、未変換のテキストを音声変換する新たなスレッドを生成する(1356～1514行目)

という処理を、未変換のテキストがなくなるまで繰り返しています。
そして、すべての音声変換が完了した後、配列に格納された音声データを結合して音声ファイルとして保存する、という流れです。

**Comment by sandonemaki** [comment]
ありがとうございます！
丁寧に説明いただけたおかげで理解が進みました。
以前よりまして複数のエンジンで動かしてみたくなりました！

文章を正規表現で整える処理をした後、未使用のサーバーをスレッドのサーバーにセットして１周回し、次の未使用サーバーをスレッドのサーバーに割り当てているんですね。
`1376` の `threads[index].value` は 戻り値、`144 voice.body` の `value` ですね。
...
`1379` の `thread_key[index]` でどの文章番号か調べ、`1389`  `output_wavdata` に格納。
これは必ず文章番号どおりになっているはず。
...
最初、デバッグした時に、スレッドの作成が３つ`（1344,1421,1506）`ある理由がわからなかったのですが、スレッドの状態を監視して、まだ音声変換されていないスレッドが残っていたら、音声変換を実行（`525` のメソッド呼び出ししてテキスト整形 -> `66` のメソッドを呼び出して API を叩いてクエリの作成、JSON 取得、音声データの取得）していたんですね。

３つのスレッド作成`（1344,1421,1506）`で引数が微妙に違うのはなぜでしょうか？
...
`1360` で １ 秒待つのは、HTTP 通信の結果を待つためと理解しました。
進捗表示するまでにスレッド（１行）毎に各１秒待っているように感じたのですが、ここだったんですね。

ちなみに１秒待たない場合は何か困ることがあるのでしょうか？

**Comment by noir55** [comment]
1344、1421行目では、ハッシュ`input_text`から未変換の文章を取り出して、それをthread_proc関数に渡して音声変換を実行しています。そして、音声変換実行中の文章はハッシュ`input_text`からは削除され、配列`thread_text`に格納されます。
1506行目は、スレッドでの音声変換が失敗し、しかも(別のエンジンで)新しいスレッドをすぐに生成できる状況である場合のスレッド再生成なので、失敗したスレッドで変換しようとしていた文章を新しいスレッドに渡しているため、上の2つとは引数が異なっています。

1360行目でsleepしているのは、HTTPでの音声変換処理は結構時間がかかる処理のため、無駄にループを回して(CPUを使って)スレッド状態をひたすらチェックしなくても(ほぼ)1秒毎にチェックするくらいでいいかと考えたためです。
sleep時間が短いほどスレッドが終了後にすぐに次のスレッド生成処理が実行される確率が高くなるので、少しでも処理を速くしたいのであればsleepをより短くするか、なくても良いと思います。

**Comment by sandonemaki** [comment]
とても丁寧にお返事いただきありがとうございます。
コードに対する解像度が以前よりも大分高くなり、その分楽しみが増えました！
ありがとうございます！
