### ISSUE TITLE
vvtts が無いと言われる

### ISSUE THREAD

**Issue by sandonemaki** [noir55/voicevox_cli_client#2]
rubyが入ったmac環境で、ターミナルから、 `% vvtts --check` をしてみましたが、動きませんでした
```
% which -a vvtts
vvtts not found
```
と出てしまいました。
voicevoxは起動させていますが、コマンドが打てないために試すことができずにいます。
大変申し訳ないのですが、こちら、どのようにしたら良いでしょうか？

**Comment by sandonemaki** [comment]
ファイル名に拡張子をつけたら動きました。

**Comment by noir55** [comment]
手元にmac環境がないため、申し訳ないのですが確認できません。解決されたとのことで、情報ありがとうございます！

**Comment by sandonemaki** [comment]
こちらこそ、ありがとうございます。
その後、他にも色々試しました。

**sox を使った再生について**
環境 mac ox Monterey ver 12.4
- mac 環境のため sox をインストールし、aplay を sox に置き換えて動かしてみたのですが、音声が再生されませんでした。
- 進捗として各行の文字出力はされ、エラーは出ず、正常に終了。

もしかしたら私のpcの問題かもしれないのですが、お伝えしておきます。

**Comment by noir55** [comment]
soxがスピーカかヘッドホンに接続されているものではないデバイスに対して音声を出力してそうな感じがします。コマンドオプションか環境変数で正しいデバイスを指定できれば再生できるかもしれません。
